### ISSUE TITLE
5장에서 얘기하는 다형성

### ISSUE THREAD

**Issue by robinjoon** [yeonjiyeon/readingstudy#6]
일반적으로 자바를 배울때 나오는 다형성(오버로딩 오버라이딩)과 이 책에서 얘기하는 다형성이 비슷하면서도 다른 느낌이 있는데 이 괴리에 대해 이야기해볼 필요가 있을듯 합니다.

**Comment by robinjoon** [comment]
오버로딩이 다형성이 아닐까?

**Comment by Snanny-Hyeon** [comment]
책에서 언급된 "다형성은 수신자의 종류를 캡슐화한다"라는 구문의 관점에서 오버로딩의 "같은 메소드라도 매개변수가 다르면 얼마든지 정의하고 사용 가능하다"라는  특징은 자바를 배울때의 다형성과 일맥상통하는 것 같습니다.

**Comment by younlll** [comment]
> 일반적으로 자바를 배울때 나오는 다형성(오버로딩 오버라이딩)과 이 책에서 얘기하는 다형성이 비슷하면서도 다른 느낌이 있는데 이 괴리에 대해 이야기해볼 필요가 있을듯 합니다.

오버로딩은 다형성의 특징을 담고 있다고 하기에 애매하다는 주장도 있다라고 알고있습니다
그래서 저는 책을 읽으면서 다형성을 오버라이딩만 연결지어서 생각을 했었네요

오버로딩에 대해서는 저도 책에서 하는 이야기와 비교해서 더 생각해봐야 할 것 같네요
